### PR TITLE
v0.2.0: following breaking API changes in bv-sized

### PR DESCRIPTION
**Pull request by Ptival**
There might be a better way of writing `word` and `int` in `Float.hs`.

Other than that, it's mostly replacing `BitVector` with `BV`.

### CODE REVIEW

**Comment by benjaminselfridge** [comment]
I know this is annoying, but can we change the names of all the functions, removing `bv` from the front, to reflect the current state of `bv-sized`?

**Comment by Ptival** [comment]
Oh yeah that sounds reasonable, let me do that!

**Comment by benjaminselfridge** [comment]
Otherwise, this looks great! No surprises.

**Comment by Ptival** [comment]
@benjaminselfridge I have tentatively done so.

Though, in `BVApp`, I have not touched the following ones: `bvAppWidth`, `bvExpr`, `bvInteger`.
Let me know what you think about these.

**Pull request merged**
